const $=i=>document.getElementById(i);let workspace,out,ready=false;const saved=localStorage.getItem('prism-v1');
function input(w=workspace){return{...w,query:[Number($('x').value),Number($('y').value)],k:Number($('k').value),radius:Number($('radius').value)}}
function compute(w=workspace){if(!ready)throw Error('Engine loading');const v=JSON.parse(globalThis.prismCompute(JSON.stringify(input(w))));if(v.error)throw Error(v.error);return v}
function text(root,tag,value){const n=document.createElement(tag);n.textContent=value;root.append(n);return n}
function render(){out=compute();$('metrics').textContent=`${out.points.length} descriptors · ${out.visited} visited · revision ${out.revision} · ${out.canonical.length} canonical`;$('hits').replaceChildren();out.hits.forEach(h=>text($('hits'),'article',`${h.id} · distance ${h.distance.toFixed(4)}`));for(const s of['a','b']){const previous=$(s).value;$(s).replaceChildren(...out.points.map(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.id;return o}));if(out.points.some(p=>p.id===previous))$(s).value=previous}$('groups').replaceChildren();out.clusters.filter(g=>g.length>1).forEach(g=>text($('groups'),'article',g.join(' ↔ ')));if(!out.clusters.some(g=>g.length>1))text($('groups'),'p','No radius candidates at this threshold');$('reviews').replaceChildren();out.reviews.forEach(r=>text($('reviews'),'article',`${r.a} + ${r.b}: ${r.decision} — ${r.note}`));const ns='http://www.w3.org/2000/svg';$('plot').replaceChildren();for(const p of out.points){const c=document.createElementNS(ns,'circle');c.setAttribute('cx',40+p.x[0]*5);c.setAttribute('cy',520-p.x[1]*5);c.setAttribute('r',out.hits.some(h=>h.id===p.id)?8:4);c.setAttribute('fill',out.hits.some(h=>h.id===p.id)?'#fa8d72':'#85a9df');const title=document.createElementNS(ns,'title');title.textContent=p.id;c.append(title);$('plot').append(c)}const cross=document.createElementNS(ns,'path');const [x,y]=input().query;cross.setAttribute('d',`M${35+x*5},${520-y*5}h10 M${40+x*5},${515-y*5}v10`);cross.setAttribute('stroke','#fff');cross.setAttribute('stroke-width','3');$('plot').append(cross)}
function operation(kind,extra){try{const next={...workspace,events:[...workspace.events,{id:`op-${Date.now()}`,revision:out.revision,kind,...extra}]};compute(next);localStorage.setItem('prism-v1',JSON.stringify(next));workspace=next;render();$('status').textContent='Saved; actual Go replay verified'}catch(e){$('status').textContent=e.message}}
function review(decision){operation('review',{a:$('a').value,b:$('b').value,decision,note:$('note').value})}function download(name,data){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
$('search').onclick=()=>{try{render();$('status').textContent='Exact search complete'}catch(e){$('status').textContent=e.message}};$('duplicate').onclick=()=>review('duplicate');$('distinct').onclick=()=>review('distinct');$('upsert').onclick=()=>operation('upsert',{point:{id:$('asset').value,x:input().query}});$('delete').onclick=()=>operation('delete',{target:$('asset').value});$('canonical').onclick=()=>download('prism-canonical.json',out.canonical);$('export').onclick=()=>download('prism-workspace.json',workspace);$('restore').onclick=()=>{try{const next=JSON.parse($('restore-data').value);compute(next);localStorage.setItem('prism-v1',JSON.stringify(next));workspace=next;render();$('status').textContent='Recovered and verified'}catch(e){$('status').textContent=e.message}};$('reset').onclick=async()=>{workspace={seed:await(await fetch('data/sample.json')).json(),events:[]};render();localStorage.setItem('prism-v1',JSON.stringify(workspace));$('status').textContent='Sample reset'};
try{const go=new globalThis.Go();const {instance}=await WebAssembly.instantiate(await(await fetch('wasm/prism.wasm')).arrayBuffer(),go.importObject);go.run(instance);ready=true;workspace=saved?JSON.parse(saved):{seed:await(await fetch('data/sample.json')).json(),events:[]};render();$('b').selectedIndex=1;$('status').textContent='Go engine ready · exact index built'}catch(e){$('status').textContent=e.message}
