import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{compile,execute,interpret,workspace}from'../lib/core.js';import handler from'../api/workspace.js';const seed=JSON.parse(readFileSync(new URL('../data/seed.json',import.meta.url)));const op=(type,payload,id='e',revision=0)=>({id,type,payload,revision});
test('VM vs independent tree interpreter: 500 seeded shipments',()=>{let s=81026;for(let i=0;i<500;i++){s=(s*1664525+1013904223)>>>0;const row={...seed.shipments[0],weight:s%40,labels:s%8,units:6,hazmat:!!(s&1),seal:!!(s&2),temperature:s%15};for(const r of compile(seed.policy))assert.equal(execute(r.code,row),interpret(r.expr,row))}});
test('Precedence and constant folding',()=>{const r=compile('require x: true or false and false message "x";')[0];assert.equal(r.code.length,1);assert.equal(execute(r.code,seed.shipments[0]),true)});
test('Strict language diagnostics and nesting budgets',()=>{for(const s of['require a: weight == true message "x";','require a: unknown < 4 message "x";','require a: constructor == constructor message "x";','require a: 2 message "x";','require a: seal < false message "x";','require a: true message "x"; require a: false message "y";','require a: '+ '('.repeat(40)+'true'+')'.repeat(40)+' message "x";'])assert.throws(()=>compile(s))});
test('Atomic quantity/schema and duplicate protections',()=>{assert.throws(()=>workspace({...seed,shipments:[{...seed.shipments[0],labels:-1}]}));assert.throws(()=>workspace({...seed,shipments:[seed.shipments[0],seed.shipments[0]]}));assert.throws(()=>workspace({...seed,events:[op('policy',{source:'broken'})]}));assert.equal(seed.events.length,0)});
test('Approval gate requires passing shipment and meaningful note',()=>{assert.throws(()=>workspace({...seed,events:[op('approve',{shipment:'DP-103',note:'reviewed'})]}));assert.throws(()=>workspace({...seed,events:[op('approve',{shipment:'DP-101',note:''})]}));assert.equal(workspace({...seed,events:[op('approve',{shipment:'DP-101',note:'Reviewed on dock'})]}).approvals['DP-101'],1)});
test('Replay deduplicates exactly; conflicts and stale revisions rejected',()=>{const e=op('approve',{shipment:'DP-101',note:'reviewed'});assert.equal(workspace({...seed,events:[e,e]}).revision,1);assert.throws(()=>workspace({...seed,events:[e,{...e,payload:{shipment:'DP-102',note:'reviewed'}}]}),/conflict/);assert.throws(()=>workspace({...seed,events:[{...e,revision:1}]}),/conflict/)});
test('Policy impact and approvals invalidated after policy or shipment edits',()=>{const a=op('approve',{shipment:'DP-101',note:'reviewed'});const r=workspace({...seed,events:[a],candidate:seed.policy.replace('weight <= 25','weight <= 17')});assert.equal(r.impact[0].changed,true);assert.equal(workspace({...seed,events:[a,op('policy',{source:seed.policy},'p',1)]}).approvals['DP-101'],undefined);assert.equal(workspace({...seed,events:[a,op('edit',{...seed.shipments[0],weight:30},'p',1)]}).approvals['DP-101'],undefined)});
test('API 200/400/405/409 and repeat equivalence',()=>{const call=(method,body)=>{const r={code:200,setHeader(){},status(n){this.code=n;return this},json(v){this.value=v;return this}};handler({method,body},r);return r};assert.equal(call('GET',seed).code,405);assert.equal(call('POST','{').code,400);assert.equal(call('POST',{...seed,events:[op('approve',{},'x',1)]}).code,409);assert.deepEqual(call('POST',seed).value,call('POST',seed).value)});
