import {test} from 'node:test';import assert from 'node:assert/strict';import {initial,apply,replay,tenantView} from '../lib/core.js';
function run(s,kind,fields={}){return apply(s,{id:`o${s.revision}`,revision:s.revision,kind,...fields})}
function seed(){return run(initial(),'enqueue',{job:'j1',tenant:'alpha',endpoint:'hook',payload:'synthetic',outcomes:[500,500,200]})}
test('Retry/circuit/recovery complete with exact journal replay',()=>{let s=seed();s=run(s,'claim',{tenant:'alpha',worker:'w'});s=run(s,'complete',{job:'j1',token:1,worker:'w'});assert.equal(s.jobs[0].due,2);s=run(s,'tick',{delta:2});s=run(s,'claim',{tenant:'alpha',worker:'w'});s=run(s,'complete',{job:'j1',token:2,worker:'w'});assert.equal(s.circuits.hook.until,10);s=run(s,'tick',{delta:4});assert.throws(()=>run(s,'claim',{tenant:'alpha',worker:'w'}),/No ready/);s=run(s,'tick',{delta:4});s=run(s,'claim',{tenant:'alpha',worker:'w'});s=run(s,'complete',{job:'j1',token:3,worker:'w'});assert.equal(s.jobs[0].status,'delivered');assert.deepEqual(replay(s.events),s)});
test('Expired worker cannot acknowledge re-leased work',()=>{let s=run(seed(),'claim',{tenant:'alpha',worker:'old'});s=run(s,'tick',{delta:5});s=run(s,'claim',{tenant:'alpha',worker:'new'});assert.throws(()=>run(s,'complete',{job:'j1',token:1,worker:'old'}),/fenced/);assert.equal(s.jobs[0].token,2)});
test('Idempotent op and conflicting retry fenced without mutation',()=>{const e={id:'i',revision:0,kind:'tick',delta:1};const s=apply(initial(),e);assert.equal(apply(s,e),s);assert.throws(()=>apply(s,{...e,delta:2}),/Conflicting/);assert.throws(()=>apply(s,{...e,id:'k'}),/Stale/)});
test('Tenant cap, isolation and permanent failure review',()=>{let s=run(initial(),'enqueue',{job:'a',tenant:'alpha',endpoint:'hook',payload:'x',outcomes:[400]});s=run(s,'enqueue',{job:'b',tenant:'beta',endpoint:'other',payload:'x',outcomes:[200]});s=run(s,'claim',{tenant:'alpha',worker:'w'});assert.throws(()=>run(s,'claim',{tenant:'alpha',worker:'z'}));assert.equal(tenantView(s,'beta').length,1);s=run(s,'complete',{job:'a',worker:'w',token:1});assert.equal(s.jobs[0].status,'dead');assert.throws(()=>run(s,'redrive',{job:'a',note:''}));s=run(s,'redrive',{job:'a',note:'Correct fixture'});assert.equal(s.jobs[0].status,'queued')});
test('Poison identifiers and budgets rejected',()=>{assert.throws(()=>run(initial(),'enqueue',{job:'__proto__',tenant:'a',endpoint:'x',payload:'',outcomes:[200]}));assert.throws(()=>run(initial(),'tick',{delta:-1}));assert.throws(()=>replay(Array(1001).fill({})))});
test('Seeded fault schedules obey terminal states and lease fencing',()=>{for(let k=0;k<150;k++){let s=run(initial(),'enqueue',{job:'a',tenant:'a',endpoint:'e',payload:'x',outcomes:[500,429,k%2?200:503]});for(let i=0;i<40;i++){const j=s.jobs[0];if(j.status==='queued'){try{s=run(s,'claim',{tenant:'a',worker:'w'})}catch{s=run(s,'tick',{delta:2})}}else if(j.status==='leased'){s=k%3===0?run(s,'tick',{delta:5}):run(s,'complete',{job:'a',worker:'w',token:j.token})}else break;}assert.ok(['dead','delivered'].includes(s.jobs[0].status));assert.deepEqual(replay(s.events),s)}});
