const $=i=>document.getElementById(i);let workspace,preview,resolutions={};let busy=false;
async function api(extra={}){const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...workspace,...extra})});const v=await r.json();if(!r.ok)throw Error(v.error);return v}
function text(parent,tag,content){const n=document.createElement(tag);n.textContent=content;parent.append(n);return n}
function show(state){$('revision').textContent=`Revision ${state.revision} · ${state.records.length} records`;$('records').replaceChildren();state.records.forEach(r=>text($('records'),'article',`${r.id} / ${r.name} / capacity ${r.capacity} / parent ${r.parent||'root'}`));$('audit').textContent=JSON.stringify(state.audit,null,2)}
async function examine(){try{const v=await api({action:'plan',base:JSON.parse($('base').value),incoming:JSON.parse($('incoming').value),resolutions});preview=v;show(v.state);$('conflicts').replaceChildren();v.plan.conflicts.forEach(c=>{const a=text($('conflicts'),'article',`${c.key}: current ${JSON.stringify(c.current)} vs incoming ${JSON.stringify(c.incoming)}`);for(const side of ['current','incoming']){const b=text(a,'button',`Keep ${side}`);b.onclick=()=>{resolutions[c.key]=side;examine()}}});$('changes').textContent=v.plan.errors.length?v.plan.errors.join('; '):`${v.plan.changes.length} changed records · ${v.plan.conflicts.length} unresolved conflicts`;$('apply').disabled=!v.plan.ready;$('status').textContent=v.plan.ready?'Plan ready for reviewed commit':'Review conflicts and dependency errors'}catch(e){$('status').textContent=e.message;$('apply').disabled=true}}
async function mutate(kind){if(busy)return;busy=true;try{const state=(await api()).state;const e={id:`op_${Date.now()}`,revision:state.revision,kind,note:$('note').value};if(kind==='merge'){if(!preview?.plan.ready)throw Error('Preview and resolve first');Object.assign(e,{base:JSON.parse($('base').value),incoming:JSON.parse($('incoming').value),resolutions,expected_hash:preview.plan.expected_hash})}const next={...workspace,events:[...workspace.events,e]};const old=workspace;workspace=next;try{const v=await api();localStorage.setItem('rivetsync-v1',JSON.stringify(workspace));preview=null;resolutions={};show(v.state);$('apply').disabled=true;$('conflicts').replaceChildren();$('changes').textContent='';$('status').textContent=`${kind==='merge'?'Committed':'Undone'}; saved journal and SQLite replay verified`}catch(e){workspace=old;throw e}}catch(e){$('status').textContent=e.message}finally{busy=false}}
function download(name,data){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
$('preview').onclick=()=>{resolutions={};examine()};$('apply').onclick=()=>mutate('merge');$('undo').onclick=()=>mutate('undo');for(const i of['base','incoming'])$(i).oninput=()=>{preview=null;resolutions={};$('apply').disabled=true};$('export').onclick=async()=>download('rivet-audit.json',(await api()).state.audit);$('download').onclick=()=>download('rivet-workspace.json',workspace);$('restore').onclick=async()=>{const old=workspace;try{workspace=JSON.parse($('restore-data').value);const v=await api();localStorage.setItem('rivetsync-v1',JSON.stringify(workspace));show(v.state);preview=null;$('apply').disabled=true;$('status').textContent='Recovered and validated'}catch(e){workspace=old;$('status').textContent=e.message}};
async function sample(){const d=await(await fetch('/data/sample.json')).json();workspace={seed:d.current,events:[]};$('base').value=JSON.stringify(d.base,null,2);$('incoming').value=JSON.stringify(d.incoming,null,2);resolutions={};localStorage.setItem('rivetsync-v1',JSON.stringify(workspace));await examine()};$('sample').onclick=sample;
try{const saved=localStorage.getItem('rivetsync-v1');if(saved){workspace=JSON.parse(saved);show((await api()).state);const d=await(await fetch('/data/sample.json')).json();$('base').value=JSON.stringify(d.base,null,2);$('incoming').value=JSON.stringify(d.incoming,null,2);$('apply').disabled=true;$('status').textContent='Saved workspace recovered'}else await sample()}catch(e){$('status').textContent=e.message}

document.querySelectorAll('button').forEach(b=>b.disabled=false);$('apply').disabled=true;
