const outside=location.pathname.includes('outside-tech');
const topics={
 city:{title:'A country built around the projects.',text:'Explore the project atlas: orbit the terrain, zoom into a district, step inside a project, and ask Pip to take you there.',url:'/projects.html',cta:'Visit the project country'},
 start:{title:'Hi, I’m Pip.',text:'Your pocket guide to Pranav’s portfolio. I can explain the projects, find a section, or take you on a quick tour.',url:outside?'/':'#home',cta:'Back to the work'},
 craftsman:{title:'CraftsmanAI, from idea to real product.',text:'Pranav is the Founder & Lead Product Architect. The platform connects custom-jewelry intake, AI-assisted design, quotes, approvals, and manufacturer handoff. The gemstone lets you explore the features one facet at a time.',url:'/#craft-explorer',cta:'Explore the gemstone'},
 experience:{title:'Engineering where reliability matters.',text:'At Fidelity, Pranav works on financial services, APIs, event processing, and analytics. His Stripe internship focused on payment components, validation, internal tools, and testing.',url:'/#experience',cta:'See the experience'},
 projects:{title:'Three projects, different kinds of complexity.',text:'CraftsmanAI connects a jewelry workflow. JMCRM-AI is a revenue-copilot prototype. The Reconciliation Engine focuses on matching operational records, aligning prices, and tracing exceptions.',url:'/#work',cta:'Explore the work'},
 crm:{title:'JMCRM-AI Revenue Copilot.',text:'A functional CRM prototype with ranked opportunities, searchable customer workflows, editable outreach, activity history, and persistent SQLite storage. Built with C#, ASP.NET Core MVC, and EF Core.',url:'/#work',cta:'See the project'},
 recon:{title:'Reconciliation Engine.',text:'A Python, SQL, and Excel/VBA framework for canonical record matching, historical price alignment, FIFO inventory aging, audit trails, and exception routing.',url:'/#work',cta:'See the project'},
 skills:{title:'The tools behind the work.',text:'React, Angular, and TypeScript for interfaces. Java, Spring Boot, Python, and Node.js for systems. OpenAI, Gemini, and RAG for practical AI. AWS, Kafka, containers, and SQL underneath.',url:'/#about',cta:'See the toolkit'},
 about:{title:'Engineer. Founder. Houston-based builder.',text:'Pranav Chirag Patel studies Computer Science at Avila University, Class of 2027. He builds full-stack software and practical AI products, and brings a founder’s perspective to the engineering.',url:'/#about',cta:'Meet Pranav'},
 resume:{title:'The full résumé, one click away.',text:'You can open or download Pranav’s résumé for his experience, projects, education, and technical skills.',url:'/assets/pranav-patel-resume.pdf',cta:'Open résumé'},
 contact:{title:'Start a conversation.',text:'Email Pranav at pranavp2418@gmail.com, or find his LinkedIn link in the contact section.',url:'mailto:pranavp2418@gmail.com',cta:'Send an email'},
 personal:{title:'Pranav, outside tech.',text:'Chess, basketball, Valorant, country life, road trips, the Houston Texans, and movies and shows. A little more competitive, a little less serious.',url:'/outside-tech.html',cta:'Explore outside tech'},
 chess:{title:'Your next opponent?',text:'Find Pranav on Chess.com as pranavthepatel. No rating claims here—settle it over the board.',url:'https://www.chess.com/member/pranavthepatel',cta:'Open Chess.com profile'},
 valorant:{title:'Reyna main. Diamond 1.',text:'Riot ID: pranav0926#3038. Diamond 1 is the rank Pranav shared on October 2, 2026; it isn’t a live tracker.',url:'/outside-tech.html#valorant',cta:'See the Valorant card'},
 instagram:{title:'A little less code.',text:'Pranav’s Instagram is @pranav_2609.',url:'https://www.instagram.com/pranav_2609/',cta:'Open Instagram'}
};
const container=document.createElement('aside');container.className='pip-guide';container.innerHTML=`<button class="pip-launcher" aria-expanded="false" aria-controls="pip-panel"><img src="/assets/bot.svg" alt=""/><span>Ask Pip</span><i></i></button><section id="pip-panel" hidden aria-label="Pip portfolio guide"><header><div><img src="/assets/bot.svg" alt=""/><span><strong>Pip</strong><small>YOUR PORTFOLIO GUIDE</small></span></div><button id="pip-close" aria-label="Close guide">×</button></header><div class="pip-content"><p class="pip-kicker">ANSWERS FROM THIS PORTFOLIO</p><h3 id="pip-title"></h3><p id="pip-answer" aria-live="polite"></p><a id="pip-action" class="pip-action"></a><div class="pip-tour" hidden><span id="pip-tour-progress"></span><div><button id="pip-prev">Back</button><button id="pip-next">Next</button><button id="pip-exit">End tour</button></div></div><div class="pip-quick"><button data-topic="craftsman">CraftsmanAI</button><button data-topic="experience">Experience</button><button data-topic="personal">Outside tech</button><button data-topic="resume">Résumé</button></div><div class="pip-tools"><button id="pip-tour-start">Take a quick tour</button><button id="pip-explain">Explain this page</button></div><form id="pip-form"><label class="sr-only" for="pip-input">Ask about Pranav or the portfolio</label><input id="pip-input" placeholder="Ask about a project, skill, or hobby…" maxlength="300" autocomplete="off"/><button type="submit" aria-label="Ask Pip">Send</button></form><p class="pip-footnote">A guided site companion. No messages are sent or stored.</p></div></section>`;document.body.append(container);
const panel=container.querySelector('#pip-panel'),launcher=container.querySelector('.pip-launcher');
function open(){panel.hidden=false;launcher.setAttribute('aria-expanded','true')}
function close(){panel.hidden=true;launcher.setAttribute('aria-expanded','false');launcher.focus()}
launcher.addEventListener('click',()=>panel.hidden?open():close());container.querySelector('#pip-close').addEventListener('click',close);container.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
function answer(key){const t=topics[key];container.querySelector('#pip-title').textContent=t.title;container.querySelector('#pip-answer').textContent=t.text;const a=container.querySelector('#pip-action');a.textContent=t.cta;a.href=t.url;a.hidden=false;if(t.url.startsWith('http')||key==='resume'){a.target='_blank';a.rel='noopener'}else a.removeAttribute('target')}
container.querySelectorAll('[data-topic]').forEach(b=>b.addEventListener('click',()=>{endTour();answer(b.dataset.topic)}));
function currentTopic(){if(outside)return'personal';const ids=[['home','start'],['work','projects'],['experience','experience'],['about','about'],['contact','contact']];let topic='start';for(const[id,key]of ids){if(document.getElementById(id)?.getBoundingClientRect().top<innerHeight*.5)topic=key}return topic}
container.querySelector('#pip-explain').addEventListener('click',()=>{endTour();answer(currentTopic())});
let tour=-1;const tourSteps=outside?['personal','chess','valorant','instagram']:['projects','craftsman','experience','skills','personal','contact'];
function endTour(){tour=-1;container.querySelector('.pip-tour').hidden=true}
function showTour(){const key=tourSteps[tour];answer(key);container.querySelector('.pip-tour').hidden=false;container.querySelector('#pip-tour-progress').textContent=`STOP ${tour+1} OF ${tourSteps.length}`;container.querySelector('#pip-prev').disabled=tour===0;container.querySelector('#pip-next').textContent=tour===tourSteps.length-1?'Finish':'Next';if(!outside&&topics[key].url.startsWith('/#'))document.querySelector(topics[key].url.slice(1))?.scrollIntoView({behavior:document.documentElement.classList.contains('no-motion')?'instant':'smooth'});if(outside&&key==='valorant')document.querySelector('#valorant')?.scrollIntoView({behavior:'smooth'})}
container.querySelector('#pip-tour-start').addEventListener('click',()=>{tour=0;showTour()});container.querySelector('#pip-prev').addEventListener('click',()=>{if(tour>0){tour--;showTour()}});container.querySelector('#pip-next').addEventListener('click',()=>{if(tour<tourSteps.length-1){tour++;showTour()}else{endTour();answer('contact')}});container.querySelector('#pip-exit').addEventListener('click',endTour);
const patterns=[['city',/terrain|city|map|atlas|district/],['craftsman',/craft|jewel|gem|founder|startup|business/],['crm',/crm|revenue|sales|opportunit/],['recon',/reconcil|pricing|fifo|inventory/],['valorant',/valorant|reyna|riot|rank|diamond/],['chess',/chess/],['instagram',/instagram|insta/],['resume',/resume|résumé|cv|download/],['experience',/fidelity|stripe|experience|career|payment|job|latency/],['skills',/skill|stack|tech|python|java|react|cloud|aws|language/],['contact',/contact|email|hire|reach|linkedin|talk/],['personal',/hobb|basketball|texan|movie|show|road|country|hiking|trail|outside|fun|personal/],['about',/who|pranav|education|college|university|graduat|houston|about/],['projects',/project|work|build/],['start',/hello|hi\b|help|hey/]];
container.querySelector('#pip-form').addEventListener('submit',e=>{e.preventDefault();const input=container.querySelector('#pip-input'),q=input.value.trim();if(!q)return;endTour();const found=patterns.find(([,p])=>p.test(q.toLowerCase()));if(found)answer(found[0]);else{container.querySelector('#pip-title').textContent='Let’s keep it to the portfolio.';container.querySelector('#pip-answer').textContent='I can explain CraftsmanAI, the other projects, experience, skills, hobbies, or how to contact Pranav. Try “What did he build?” or choose a topic below.';container.querySelector('#pip-action').hidden=true}input.value=''});
answer(outside?'personal':'start');
