let workspace,result;const $=x=>document.getElementById(x),key='permitweave-v1';
const escape=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function compute(next){document.body.classList.add('busy');$('status').textContent='Validating and allocating…';try{const response=await fetch('/api/compute',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});const value=await response.json();if(!response.ok)throw Error(value.error);localStorage.setItem(key,JSON.stringify(next));workspace=next;result=value;render();$('status').textContent=`Workspace saved · revision ${value.revision} · ${value.allocation.covered} visits allocated`;}catch(e){$('status').textContent='Unable to apply: '+e.message;}finally{document.body.classList.remove('busy');}}
function render(){const a=result.allocation;$('metrics').innerHTML=[['Covered visits',a.covered],['Coverage gaps',a.uncovered],['Audit revision',result.revision]].map(([l,n])=>`<div class="metric"><strong>${n}</strong>${l}</div>`).join('');const selected=$('auth').value;$('auth').innerHTML=result.state.authorizations.map(x=>`<option value="${escape(x.id)}">${escape(x.id)} · ${escape(x.member)}</option>`).join('');if(selected)$('auth').value=selected;$('windows').innerHTML=result.state.authorizations.map(x=>{const unused=a.remaining[x.id];return `<div class="window"><b>${escape(x.id)}</b> · ${escape(x.member)}<br>${escape(x.start)} — ${escape(x.end)}<div class="bar"><i style="width:${x.units?100*(x.units-unused)/x.units:0}%"></i></div>${x.units-unused} used / ${x.units} units</div>`}).join('');const members=[...new Set(result.state.visits.map(v=>v.member))];$('map').innerHTML=members.map(m=>`<div class="rowmap"><span>${escape(m)}</span>${a.assignments.filter(x=>result.state.visits.find(v=>v.id===x.visit).member===m).map(x=>`<div class="block ${x.authorization?'':'gap'}" role="img" aria-label="${escape(x.visit+': '+(x.authorization||x.reason))}" title="${escape(x.visit+': '+(x.authorization||x.reason))}"></div>`).join('')}</div>`).join('');rows();$('history').innerHTML=result.audit.length?result.audit.map(x=>`<li>Revision ${x.revision}: ${escape(x.event.authorization)} → ${x.event.units} units<br><code>${x.hash}</code></li>`).join(''):'<li>No capacity edits. Baseline allocation computed.</li>';}
function rows(){if(!result)return;$('visits').innerHTML=result.allocation.assignments.filter(x=>$('filter').value==='all'||!x.authorization).map(x=>`<tr><td>${escape(x.visit)}</td><td>${escape(x.date)}</td><td>${escape(x.authorization||x.reason.replaceAll('_',' '))}</td></tr>`).join('')||'<tr><td colspan="3">No visits in this view.</td></tr>';}
$('edit').onsubmit=e=>{e.preventDefault();if(!workspace)return;const next=structuredClone(workspace);next.events.push({key:crypto.randomUUID(),type:'capacity',authorization:$('auth').value,units:Number($('units').value),expected_revision:result.revision});compute(next);};$('filter').onchange=rows;
async function reset(){try{await compute({data:await (await fetch('data/seed.json')).json(),events:[]})}catch(e){$('status').textContent=e.message}}$('reset').onclick=reset;
$('export').onclick=()=>{if(!workspace)return;const url=URL.createObjectURL(new Blob([JSON.stringify(workspace,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='permitweave-workspace.json';a.click();URL.revokeObjectURL(url)};
$('import').onchange=async e=>{try{if(e.target.files[0].size>200000)throw Error('Import exceeds 200 KB');await compute(JSON.parse(await e.target.files[0].text()))}catch(err){$('status').textContent='Import failed: '+err.message}};
try{const saved=JSON.parse(localStorage.getItem(key));if(saved)await compute(saved);else await reset()}catch(e){await reset()}
